//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekz_Sedov.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public string nomer { get; set; }
        public string name { get; set; }
        public string ed { get; set; }
        public decimal price { get; set; }
        public int maxSkidka { get; set; }
        public string maker { get; set; }
        public string postav { get; set; }
        public string category { get; set; }
        public int skidka { get; set; }
        public int count { get; set; }
        public string description { get; set; }
        public string image { get; set; }
    }
}
